#!/bin/bash

######################################################
######################################################
########## script para copiar via terminal############
######################################################
######################################################

########## verifica se recebeu 1 argumento ###########
if [ $# -ne 1 ]; then
        echo "Usage: copy FILE"
        exit 1
fi

if [ -d $1 ]; then
       echo "The provided argument is the directory."
       exit 1
fi

########## copia o conteudo do arquivo ###############
xclip -i -sel copy $1

########## avisa que o conteudo foi copiado ##########
echo "arquivo copiado com sucesso"
